# Generated by Django 2.2.4 on 2023-02-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('entity', models.CharField(max_length=32)),
                ('amount', models.CharField(max_length=8)),
                ('amount_paid', models.CharField(max_length=8)),
                ('amount_due', models.CharField(max_length=8)),
                ('currency', models.CharField(max_length=8)),
                ('receipt', models.CharField(max_length=32)),
                ('offer_id', models.CharField(max_length=32, null=True)),
                ('status', models.CharField(max_length=32)),
                ('attempts', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
