# Generated by Django 2.2.4 on 2022-03-26 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20191014_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=40, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount_due',
            field=models.CharField(default=40, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='attempts',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='entity',
            field=models.CharField(default='order', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='offer_id',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.CharField(default='auuIXBomaKEVAn5', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
