# Generated by Django 2.2.4 on 2022-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20220326_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
