# Generated by Django 2.2.4 on 2022-04-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='nontech_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='wait_duration',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
