# Generated by Django 2.2.4 on 2022-04-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20220424_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='upload',
        ),
    ]
