version: "3"

services:
  frontend:
    depends_on:
      - backend
    # env_file: client/.env
    # build:
    #   context: client
    image: hmx098/techtrek2023_frontend
    networks:
      - default
    ports:
      - 4096:80

  backend:
    restart: always
    image: hmx098/tech_trek_backend
    env_file: .env
    ports:
      - 8099:8000
    volumes:
      - type: volume
        source: database
        target: /techtrek/database/

volumes:
  database:
