version: "3"

services:
  frontend2023:
    depends_on:
      - backend2023
    # env_file: client/.env
    # build:
    #   context: client
    image: hmx098/techtrek2023_frontend:v2
    networks:
      - default
    ports:
      - 4096:80

  backend2023:
    restart: always
    image: hmx098/tech_trek_backend:testingv3
    env_file: 
      - stack.env
    ports:
      - 8099:8000
    volumes:
      - type: volume
        source: techdatabase
        target: /techtrek/database/

volumes:
  techdatabase:
