# Generated by Django 2.2.4 on 2023-04-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
