# Generated by Django 2.2.4 on 2023-04-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230410_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tezos_wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
