# Generated by Django 2.2.4 on 2022-04-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191014_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='technical_solved',
            field=models.IntegerField(default=0),
        ),
    ]
