# Generated by Django 2.2.4 on 2022-04-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_player_technical_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='avatar_no',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_paid',
        ),
    ]
