# Generated by Django 2.2.4 on 2022-04-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_auto_20191015_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('0', 'special'), ('1', 'level1'), ('2', 'level2'), ('3', 'level3'), ('4', 'level4'), ('5', 'level5'), ('6', 'level6')], max_length=1),
        ),
    ]
